<?php
/*******************************************
 *
 * 2016 - Sistemas de Informacion Basados en Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <erseco@correo.ugr.es>
 * Nikolai Giovanni González López <nigolo@correo.ugr.es>
 *
 *
 *******************************************
 *
 * Mostramos la información básica de PHP
 *
 ******************************************************************************/
?>

<br />

<div id="phpinfo" class="container">

<?php

//Capturamos la salida de phpinfo()
ob_start();
phpinfo(INFO_GENERAL);
$phpinfo = ob_get_clean();


//Le quitamos html que no desbarajusta nuestro propio estilo
$phpinfo = preg_replace('#^.*<body>(.*)</body>.*$#s', '$1', $phpinfo);

$phpinfo = str_replace('module_Zend Optimizer', 'module_Zend_Optimizer', $phpinfo);

//Reemplazamos <font> por <span>
$phpinfo = str_replace('<font', '<span', $phpinfo);
$phpinfo = str_replace('</font>', '</span>', $phpinfo);

//Tabla
$phpinfo = str_replace( 'border="0" cellpadding="3"', 'class="table table-bordered table-striped" style="table-layout: fixed;word-wrap: break-word;"', $phpinfo );
$phpinfo = str_replace('<tr class="h"><th>', '<thead><tr><th>', $phpinfo);
$phpinfo = str_replace('</th></tr>', '</th></tr></thead><tbody>', $phpinfo);
$phpinfo = str_replace('</table>', '</tbody></table>', $phpinfo);

//Coloreamos palabras clave en verde o rojo
$phpinfo = preg_replace('#>(on|enabled|active)#i', '><span class="text-success">$1</span>', $phpinfo);
$phpinfo = preg_replace('#>(off|disabled)#i', '><span class="text-error">$1</span>', $phpinfo);

//Lo mostramos
echo $phpinfo;

?>
    </div> <!-- /container -->

