<?php
/*******************************************
 *
 * 2016 - Sistemas de Informacion Basados en Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <erseco@correo.ugr.es>
 * Nikolai Giovanni González López <nigolo@correo.ugr.es>
 *
 *
 *******************************************
 *
 *  Pagina de inicio de sesión
 *
 ******************************************************************************/
?>

    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title"><?php _e('Sign in to continue to') ?> <?php echo SITE_NAME; ?></h1>
            <div class="account-wall">
                <img class="profile-img" src="assets/profile.png"
                    alt="profile image">
                <form class="form-signin" method="post">

                <?php if ($error) : ?>
                <div class="alert alert-danger alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <strong>Error!</strong> <?php _e('Check your login data') ?>.
                </div>
                <?php endif; ?>


                <input type="email" name="email" class="form-control" placeholder="<?php _e('Email') ?>" value="<?php if ($error) echo $_POST['email']; ?>" required autofocus>
                <input type="password" name="password" class="form-control" placeholder="<?php _e('Password') ?>" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                   <?php _e('Sign in') ?></button>
                <label class="checkbox pull-left">
                    <input type="checkbox" name="remember" value="0">
                    <?php _e('Remember me') ?>
                </label>



                <a href="mailto:info@ernesto.es?subject=Login%20problem" class="pull-right need-help">Need help? </a><span class="clearfix"></span>

<div>
                <p><strong>User:</strong> admin@ernesto.es<br /><strong>Password:</strong> admin1234</p>
                <p><strong>User:</strong> user@ernesto.es<br /><strong>Password:</strong> user1234</p>
</div>

                </form>


            </div>
        </div>
    </div>
