<?php
/*******************************************
 *
 * 2016 - Sistemas de Informacion Basados en Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <erseco@correo.ugr.es>
 * Nikolai Giovanni González López <nigolo@correo.ugr.es>
 *
 *
 *******************************************
 *
 * Créditos de la página
 *
 ******************************************************************************/
?>

<div class="col-md-9">

<h2><?php echo $page_title; ?></h2>

<p><strong><?php echo SITE_NAME; ?></strong> is developed for the course of <strong>Sistemas de Informacion Basados en Web</strong> at the <a href="http://www.ugr.es" target="_blank"><abbr title="University of Granada">UGR</abbr></a> by the students:</p>
	<ul>
		<li>Ernesto Serrano &lt;<a href="mailto:erseco@correo.ugr.es">erseco@correo.ugr.es</a>&gt;</li>
		<li>Nikolai Giovanni Gonzalez &lt;<a href="nigolo@correo.ugr.es">nigolo@correo.ugr.es</a>&gt;</li>
	</ul>
<br />
<p><strong><?php echo SITE_NAME; ?></strong> is developed using the next technologies, frameworks and libraries:</p>
<div class="row">
  <div class="col-md-9">
	<h3>Technologies</h3>
	<ul>
	<li>HTML5</li>
	<li>CSS3</li>
	<li>Javascript 1.3</li>
	<li>PHP 5.5</li>
	<li>MySQL 5.5</li>
	</ul>

	<h3>Frameworks</h3>
	<ul>
	<li>Twitter Bootstrap</li>
	</ul>

	<h3>Libraries</h3>
	<ul>
	<li>jQuery</li>
	<li>baguetteBox.js</li>
	<li>Date Range Picker</li>
	<li>Moment.js</li>
	</ul>

	<h3>Schematics</h3>
	<img class="img-responsive" src="assets/er.png" />

  </div>

</div>








</div>



