<?php
/*******************************************
 *
 * 2016 - Sistemas de Informacion Basados en Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <erseco@correo.ugr.es>
 * Nikolai Giovanni González López <nigolo@correo.ugr.es>
 *
 *
 *******************************************
 *
 *  Pagina home, esta la que se ve despues de iniciar sesión
 *
 ******************************************************************************/
?>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="col-md-8">
        <h1><?php echo SITE_NAME ?></h1>
        <?php _e('HOME_DESCRIPTION') ?>
        <hr>
    </div>
