            <!-- Map Column -->
            <div class="col-md-9">
                <!-- Embedded Google Map -->
                <iframe width="100%" height="500px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.17704,-3.596301&amp;spn=56.506174,79.013672&amp;t=m&amp;z=18&amp;output=embed"></iframe>
            </div>
            <!-- Contact Details Column -->